package com.myspace.leave_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Approval implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long approvalId;
	private com.myspace.leave_demo.Leave leave;
	private com.myspace.leave_demo.Employee employee;
	private java.lang.String status;

	public Approval() {
	}

	public java.lang.Long getApprovalId() {
		return this.approvalId;
	}

	public void setApprovalId(java.lang.Long approvalId) {
		this.approvalId = approvalId;
	}

	public com.myspace.leave_demo.Leave getLeave() {
		return this.leave;
	}

	public void setLeave(com.myspace.leave_demo.Leave leave) {
		this.leave = leave;
	}

	public com.myspace.leave_demo.Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(com.myspace.leave_demo.Employee employee) {
		this.employee = employee;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public Approval(java.lang.Long approvalId,
			com.myspace.leave_demo.Leave leave,
			com.myspace.leave_demo.Employee employee, java.lang.String status) {
		this.approvalId = approvalId;
		this.leave = leave;
		this.employee = employee;
		this.status = status;
	}

}