package com.myspace.leave_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Department implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long departmentId;
	private java.lang.String name;
	private Employee employee;

	public Department() {
	}

	public java.lang.Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(java.lang.Long departmentId) {
		this.departmentId = departmentId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public com.myspace.leave_demo.Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(com.myspace.leave_demo.Employee employee) {
		this.employee = employee;
	}

	public Department(java.lang.Long departmentId, java.lang.String name,
			com.myspace.leave_demo.Employee employee) {
		this.departmentId = departmentId;
		this.name = name;
		this.employee = employee;
	}

}