package com.myspace.leave_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.leave_demo.Employee> employeeList;

	public EmployeeList() {
	}

	public java.util.List<com.myspace.leave_demo.Employee> getEmployeeList() {
		return this.employeeList;
	}

	public void setEmployeeList(
			java.util.List<com.myspace.leave_demo.Employee> employeeList) {
		this.employeeList = employeeList;
	}

	public EmployeeList(
			java.util.List<com.myspace.leave_demo.Employee> employeeList) {
		this.employeeList = employeeList;
	}

}