package com.myspace.leave_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Leave implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long leaveId;
	private com.myspace.leave_demo.Employee emp;
	private java.lang.String status;
	private Approval approval;

	public Leave() {
	}

	public java.lang.Long getLeaveId() {
		return this.leaveId;
	}

	public void setLeaveId(java.lang.Long leaveId) {
		this.leaveId = leaveId;
	}

	public com.myspace.leave_demo.Employee getEmp() {
		return this.emp;
	}

	public void setEmp(com.myspace.leave_demo.Employee emp) {
		this.emp = emp;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public com.myspace.leave_demo.Approval getApproval() {
		return this.approval;
	}

	public void setApproval(com.myspace.leave_demo.Approval approval) {
		this.approval = approval;
	}

	public Leave(java.lang.Long leaveId, com.myspace.leave_demo.Employee emp,
			java.lang.String status, com.myspace.leave_demo.Approval approval) {
		this.leaveId = leaveId;
		this.emp = emp;
		this.status = status;
		this.approval = approval;
	}

}